version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: cosmoally-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cosmoally
      MYSQL_USER: akash
      MYSQL_PASSWORD: "@Aakash2904"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cosmo-network

  backend:
    build: .
    container_name: cosmoally-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cosmoally?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: akash
      SPRING_DATASOURCE_PASSWORD: "@Aakash2904"
    depends_on:
      - db
    networks:
      - cosmo-network

volumes:
  db_data:

networks:
  cosmo-network:
